sudo: false
language: node_js
node_js:
  - "6.11.4"
  - "6.10.3"
  - "6"

env:
  global:
    - MONGODB_VERSION=3.2.4

install:
  - ./.travis/install.sh
  - export PATH="/tmp/usr/bin:${PATH}"
  - npm install -g npm@3.10.10
  - npm install -g grunt-cli@1.2.0
  - npm install -g bower@1.8.2
  - npm install
  - bower install

before_script:
  - node --version
  - npm --version
  - mongo --version

script:
  - if [ "${RUN_COVERAGE}" = "true" ]; then grunt -v test_coverage; else grunt -v; fi

after_script:
  - cat /tmp/*/test_db.log
